-- RunMCP D1 source of truth. D1 has no RLS: the Worker verifies the OIDC
-- subject and scopes every query by user_id.
create table profiles (user_id text primary key, display_name text, timezone text not null default 'UTC', preferred_unit text not null default 'mi' check(preferred_unit in ('mi','km')), training_intensity text not null default 'balanced' check(training_intensity in ('conservative','balanced','ambitious')), planning_notes text, created_at text not null, updated_at text not null);
create table goals (id text primary key, user_id text not null, name text not null, distance_type text not null, distance_value real, distance_unit text not null, target_date text not null, target_pace text, status text not null default 'active' check(status in ('active','completed','cancelled')), created_at text not null, updated_at text not null);
create index goals_user_status on goals(user_id,status,target_date);
create table plan_series (id text primary key, user_id text not null unique, current_version integer not null default 0, created_at text not null, updated_at text not null);
create table plan_versions (id text primary key, user_id text not null, plan_series_id text not null, version integer not null, status text not null check(status in ('current','superseded')), reason text not null, rationale text not null, created_at text not null, unique(plan_series_id,version));
create table plan_version_goals (plan_version_id text not null, goal_id text not null, name text not null, distance_type text not null, distance_value real, distance_unit text not null, target_date text not null, target_pace text, primary key(plan_version_id,goal_id));
create table planned_workouts (id text primary key, user_id text not null, plan_version_id text not null, scheduled_date text not null, kind text not null, title text not null, summary text, created_at text not null, unique(plan_version_id,scheduled_date));
create table workout_sections (id text primary key, planned_workout_id text not null, position integer not null, section_type text not null check(section_type in ('instruction','warmup','main','recovery','cooldown','rest')), repeat_count integer not null default 1 check(repeat_count > 0), note text, unique(planned_workout_id,position));
create table workout_steps (id text primary key, workout_section_id text not null, position integer not null, action text not null check(action in ('run','walk','rest','stretch','other')), target_distance real, target_distance_unit text, target_duration_seconds integer, target_pace text, max_pace text, target_effort integer check(target_effort between 1 and 10), instruction text, unique(workout_section_id,position));
create table actual_runs (id text primary key, user_id text not null, planned_workout_id text unique, performed_at text not null, distance real not null check(distance > 0), distance_unit text not null, duration_seconds integer not null check(duration_seconds > 0), perceived_effort integer check(perceived_effort between 1 and 10), user_note text, completion_status text not null default 'completed' check(completion_status in ('completed','partial','modified','extra')), agent_interpretation text, match_status text not null default 'unmatched' check(match_status in ('unmatched','agent_linked','confirmed')), match_rationale text, created_at text not null, updated_at text not null);
create index actual_runs_user_date on actual_runs(user_id,performed_at);
create table availability_rules (id text primary key, user_id text not null, weekday integer check(weekday between 0 and 6), start_date text, end_date text, rule text not null check(rule in ('unavailable','avoid','prefer')), workout_kind text, max_distance real, max_duration_seconds integer, note text, active integer not null default 1, created_at text not null, updated_at text not null, check(weekday is not null or start_date is not null));
create table activities (id text primary key, user_id text not null, occurred_at text, name text not null, type text not null, intensity text, note text, created_at text not null, updated_at text not null);
create table interruptions (id text primary key, user_id text not null, start_date text not null, end_date text, reason text not null, note text, created_at text not null, updated_at text not null);
create table agent_connections (id text primary key, user_id text not null, client_id text not null, provider text not null, status text not null default 'active' check(status in ('active','revoked')), first_seen_at text not null, last_seen_at text not null, revoked_at text, unique(user_id,client_id));
create table audit_events (id text primary key, user_id text not null, action text not null, entity_type text, entity_id text, metadata text not null default '{}', created_at text not null);
create index audit_events_user_created on audit_events(user_id,created_at);
